[theme]
base = "dark"
primaryColor="#F63366"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
headless = true

[runner]
magicEnabled = false

[global]
hideMenu = true
hideFooter = true